$primary = rgb(a7c080)
$surface = rgb(232a2e)
$secondary = rgb(d3c6aa)
$error = rgb(e67e80)
$tertiary = rgb(9da9a0)
$surface_lowest = rgb(252c30)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
