-- Generated by HyprMod

-- Settings
hl.config({
    decoration = {
        blur = {
            noise = 0.011,
            passes = 3,
            size = 5,
            xray = true,
        },
        rounding = 3,
    },
    general = {
        border_size = 2,
    },
    xwayland = {
        force_zero_scaling = true,
    },
})
